fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.7.0"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat"
      ref: "1.2.4"
    collectd:
      repo: "git://github.com/puppet-community/puppet-collectd"
      ref: "v4.1.2"
    apache:
      repo: "git://github.com/puppetlabs/puppetlabs-apache"
      ref: "1.4.0"
  symlinks:
    lma_collector: "#{source_dir}"
    heka: "#{source_dir}/../heka"
