#!/bin/bash
# Copyright 2016 Mirantis, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NODES_LIST_FILE=/tmp/nodes

if [ ! -f "${NODES_LIST_FILE}" ]; then
  echo "You must run the following command on Fuel master node before:"
  echo "  fuel nodes > ${NODES_LIST_FILE}"
  echo "You should run this script by saving its output:"
  echo "  ${0} | tee /tmp/upgrade_0.8.0_to_0.8.1.log"
  exit 1
fi

# Remove Heka due to the issue with heka package versionning
# https://github.com/mozilla-services/heka/issues/1892
echo "** Upgrading Heka to 0.10.0"
for n in $(grep True $NODES_LIST_FILE|grep ready|awk -F '|' '{print $5}'); do
    echo "$n";
    ssh "$n" 'apt-get remove -y heka'
done
