# Copyright 2015 Mirantis, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
source 'https://rubygems.org'

group :development, :test do
  gem 'rake'
  gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.4.0'
  gem 'puppetlabs_spec_helper'
  # Need to use master branch of puppet-lint because of
  # https://github.com/rodjek/puppet-lint/issues/355
  gem 'puppet-lint', :git => 'https://github.com/rodjek/puppet-lint.git'
end
